version: '3'

services:
  api:
    build: .
    ports:
      - '9292:9292'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    image: postgres:12.3
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5435:5432'

volumes:
  db_data:
